[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
payment_processor = "8D6DNFXjHFDG2Lgaw84uh111YxtYpJ3yaJJehRpbjt83"

[programs.devnet]
payment_processor = "8D6DNFXjHFDG2Lgaw84uh111YxtYpJ3yaJJehRpbjt83"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"                # "devnet || localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
setup = "rustup update nightly && cargo update -p anchor-lang -p proc-macro2 && avm use 0.31.1 && agave-install init 2.2.6"
